### ISSUE TITLE
delete this, or I'm reporting you

### ISSUE THREAD

**Issue by CHUCKECHEESETubeYT** [AbnormalPoof/Sonic-3-2022-Decompilation#1]
this is sick & wrong, you can't just go ahead & post bullshit like this! besides, people have been waiting for a Sonic 3 decomp from origins for too. fucking. LONG! even i have too! & posting shit like this will only make it worse! not only that, but I'm sick & tired of these trolls, scams & support for shit THAT DOESN'T DESERVE TO FUCKING EXIST! IT DESERVES TO FUCKING DIE & STAY FUCKING DEAD & ABANDONED! you must understand, this, will not help anyone, it will do harm & be an insult to those who just want to see a decomp from origins to fulfill a destiny, a dream & so much more, if you can't do that, then WHY THE FUCK ARE YOU EVEN HERE!? regardless, making a scene like this will be a disappointment not just for anyone else, but yourself, if you keep this up, you'll forever be, nothing but a disappointment to everyone & your family, ik you don't have a FUCKING HEART at all, you disgust me, i just wish a decomp from sonic origins, to forget @!4 ever existed & so won't need to see it again, but no one has been willing to help me, not even force, why do i even try, it's not like it'll get me anywhere, i had to learn that the hard way once before & nowadays, I'm retired from so many things, but you on the other hand, have made my search EVEN. FUCKING. HARDER! SO DELETE THIS, OR I'LL DO IT, FOR YOU!

**Comment by AbnormalPoof** [comment]
https://store.steampowered.com/app/1794960/Sonic_Origins/
https://ghidra-sre.org/
